#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom assertthat assert_that
#' @importFrom data.table melt
#' @importFrom data.table setDT
#' @importFrom graphics abline
#' @importFrom grDevices colorRampPalette
#' @importFrom methods formalArgs
#' @importFrom parallel clusterExport
#' @importFrom parallel parLapply
#' @importFrom parallel parLapplyLB
#' @importFrom pbapply pblapply
#' @importFrom raster as.matrix
#' @importFrom raster distanceFromPoints
#' @importFrom raster raster
#' @importFrom stats approx
#' @importFrom stats getCall
#' @importFrom stats quantile
#' @importFrom stats reshape
#' @importFrom stats rgeom
#' @importFrom stats rlnorm
#' @importFrom stats rnorm
#' @importFrom stats rpois
#' @importFrom terra app
#' @importFrom terra classify
#' @importFrom terra compareGeom
#' @importFrom terra crs
#' @importFrom terra crs<-
#' @importFrom terra distance
#' @importFrom terra ext
#' @importFrom terra extract
#' @importFrom terra ncell
#' @importFrom terra nlyr
#' @importFrom terra nlyr<-
#' @importFrom terra plot
#' @importFrom terra rast
#' @importFrom terra res
#' @importFrom terra res<-
#' @importFrom terra setValues
#' @importFrom terra spatSample
#' @importFrom terra subset
#' @importFrom terra unwrap
#' @importFrom terra values
#' @importFrom terra values<-
#' @importFrom terra vect
#' @importFrom terra wrap
#' @importFrom terra xmax
#' @importFrom terra xmin
#' @importFrom terra xyFromCell
#' @importFrom terra ymax
#' @importFrom terra ymin
#' @importFrom utils setTxtProgressBar
#' @importFrom utils txtProgressBar
#' @importFrom zoo na.approx
## usethis namespace: end
NULL
